version: '3.1'

services:

  database:
    image: mongo
    container_name: my-mongo-container
    restart: always
    environment:
      MONGO_INITDB_ROOT_DATABASE: mydb
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017